// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
//
// about entry points, see forge.config.js
declare const MAIN_PRELOAD_WEBPACK_ENTRY: string;
declare const MAIN_WEBPACK_ENTRY: string;

declare const SPLASH_PRELOAD_WEBPACK_ENTRY: string;
declare const SPLASH_WEBPACK_ENTRY: string;

declare const LECTURE_PRELOAD_WEBPACK_ENTRY: string;
declare const LECTURE_WEBPACK_ENTRY: string;
